---

- name: Set Ansible Python interpreter
  set_fact:
    ansible_python_interpreter: /usr/bin/python3
  when: ansible_distribution_major_version|int == 10

- name: install MariaDB client + server
  apt:
    pkg: "{{ mariadb_packages }}"
    state: present
    update_cache: true
  notify: remove MariaDB test database

- name: install python-pymysql
  apt:
    pkg: python-pymysql
  when: ansible_distribution_major_version|int <= 9

- name: optionally install automysqlbackup
  apt:
    pkg: "automysqlbackup"
    state: present
  when: mariadb_automysqlbackup

- name: optionally install automysqlbackup
  apt:
    pkg: "mariadb-backup"
    state: present
  when: mariadb_backup and ansible_distribution_major_version|int >= 10

- name: start MariaDB
  service:
    name: mysql
    state: started

- name: configure MariaDB server
  template:
    src: etc/mysql/mariadb.conf.d/60-server.cnf.j2
    dest: /etc/mysql/mariadb.conf.d/60-server.cnf
    owner: root
    group: root
    mode: 0644
  notify: restart mysql
  tags:
    - role:mariadb:config

- name: configure MariaDB backup
  template:
    src: etc/mysql/mariadb.conf.d/70-backup.cnf.j2
    dest: /etc/mysql/mariadb.conf.d/70-backup.cnf
    owner: root
    group: root
    mode: 0644
  tags:
    - role:mariadb:config
  when: mariadb_backup and ansible_distribution_major_version|int >= 10

- name: ensure databases are present
  mysql_db:
    name: "{{ item }}"
    login_unix_socket: /run/mysqld/mysqld.sock
  with_items: "{{ mariadb_databases }}"

- name: Run handlers if needed
  meta: flush_handlers

- name: create additional MariaDB users
  mysql_user:
    name: "{{ item.name }}"
    host: "{{ item.host|default('localhost') }}"
    password: "{{ item.password }}"
    priv: "{{ item.priv }}"
    login_unix_socket: /run/mysqld/mysqld.sock
  no_log: true
  with_items:
    - "{{ mariadb_users }}"

- include_tasks: replication.yml
  when: mariadb_replication_master or mariadb_replication_slave
  tags:
    - mariadb_replication

- include_tasks: munin.yml
  when: mariadb_munin
  tags:
    - munin
