---
- name: Ensure munin-plugins-core is installed (on stretch from stretch-backports)
  ansible.builtin.apt:
    name: munin-plugins-core
    state: present

- name: Ensure munin perl packages are installed
  ansible.builtin.apt:
    pkg: "{{ item }}"
    state: present
  loop:
    - libcache-perl
    - libcache-cache-perl

- name: Ensure common plugins are present
  ansible.builtin.file:
    src: "/usr/share/munin/plugins/mysql_"
    dest: "/etc/munin/plugins/mysql_{{ item }}"
    state: link
  loop:
    - commands
    - qcache
    - network_traffic
  notify: Restart munin-node

- name: Ensure mysql plugin config is present
  ansible.builtin.template:
    src: munin/plugin-conf.d/mysql.j2
    dest: /etc/munin/plugin-conf.d/mysql
    owner: root
    group: root
    mode: "0644"
