---

- name: Run handlers if needed
  meta: flush_handlers

- name: create replication user
  mysql_user:
    name: "{{ mariadb_replication_user_local.name }}"
    host: "{{ mariadb_replication_user_local.host|d('%') }}"
    password: "{{ mariadb_replication_user_local.pass }}"
    priv: "*.*:REPLICATION SLAVE"
    state: present
  when: mariadb_replication_master and mariadb_replication_user_local is defined

- name: get replication slave status
  mysql_replication:
    mode: getslave
  ignore_errors: True
  register: __mariadb_repl_slave_status
  when: mariadb_replication_slave

- name: get replication master status
  mysql_replication:
    mode: getmaster
  delegate_to: "{{ mariadb_replication_master_server }}"
  register: __mariadb_repl_master_status
  when: mariadb_replication_slave and not __mariadb_repl_slave_status.Is_Slave

- name: configure replication settings
  mysql_replication:
    mode: changemaster
    master_host: "{{ mariadb_replication_master_server }}"
    master_log_file: "{{ __mariadb_repl_master_status.File }}"
    master_log_pos: "{{ __mariadb_repl_master_status.Position }}"
    master_user: "{{ mariadb_replication_user_remote.name }}"
    master_password: "{{ mariadb_replication_user_remote.pass }}"
  when: mariadb_replication_slave and not __mariadb_repl_slave_status.Is_Slave
