---
- name: Restart mysql
  ansible.builtin.service:
    name: mysql
    state: restarted

- name: Remove MariaDB test database
  community.mysql.mysql_db:
    name: test
    state: absent
    login_unix_socket: /run/mysqld/mysqld.sock
